version: '2'
services:
  simple-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ssh_port}:22"
    volumes:
      - nvidia_vol:/usr/local/nvidia:ro
      - /usr/lib/nvidia-390:/usr/lib/nvidia-390:ro
    network_mode: bridge
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia1

volumes:
  nvidia_vol:
    external:
      driver: nvidia-docker
      name: nvidia_driver_390.46
