FROM ppc64le/ubuntu
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server cloud-init supervisor sudo locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8 

RUN mkdir -p /var/run/sshd /var/log/supervisor
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN echo 'root:root123' | chpasswd
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY cloud-init-start.sh /usr/sbin/cloud-init-start.sh

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22
CMD ["/usr/bin/supervisord"]
