#node port range is from 30,000 to 32,767
kind: Service
apiVersion: v1
metadata:
  name: ssh-service
spec:
  type: NodePort
  selector:
    app: ssh
  ports:
  - protocol: TCP
    port: 22
    nodePort: 31111
    targetPort: 22
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ssh-deployment
  labels:
    app: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: ssh
        image: bhanum2/ubuntu1604_ssh
        ports:
        - containerPort: 22

